# Cartesian product using list comprehesion 

colors = ["Black", "White"]
sizes = ["S", "M", "L"]

tshirts = [(colors, sizes) for color in colors for size in sizes]
print(tshirts)


# List of tuples generated by color, then by size
for color in colors:
    for size in sizes:
        print((color, size))


# mutable tuples may be source of bugs

a = (10, 'alpha', [1,2])
b = (10, 'alpha', [1,2])

b[-1].append(99)

print(a == b) # false




